### ISSUE TITLE
Many warnings and errors, and does not run.

### ISSUE THREAD

**Issue by raarts** [smpallen99/coherence_demo#6]
Throws a lot of `warning: variable "xxx" does not exist and is being expanded to "xxx()", please use parentheses to remove the ambiguity or change the variable name`. Many deprecation warnings, also this:

```
Unchecked dependencies for environment dev:
* coherence (../coherence)
  the dependency is not available
** (Mix) Can't continue due to errors on dependencies
```

and this:

```
warning: the Behaviour module is deprecated. Instead of using this module, use the @callback and @macrocallback module attributes.
```

In the end I can't run it because of:

```
== Compilation error on file web/views/coherence/confirmation_view.ex ==
** (CompileError) web/templates/coherence/confirmation/new.html.eex:5: undefined function confirmation_path/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.
```

**Comment by x-ji** [comment]
I had this error on `master` branch as well. However, the `canary` branch runs.

**Comment by lucca65** [comment]
Is this repo abandoned? I'm trying to run for a better understanding, but i'm having the same error as you guys, from 4 months ago

**Comment by smpallen99** [comment]
I'm working on a new version of Coherence. I'll update this repo to the new phx 1.3 structure once I get the new coherence version out.

**Comment by Tenzil** [comment]
Hi @smpallen99 , I just couldn't install your plugin, i tried for 5hours still never able to test all features you have provided. In coherence_demo when i run mix test i got the following
== Compilation error on file web/views/coherence/confirmation_view.ex ==
** (CompileError) web/templates/coherence/confirmation/new.html.eex:5: undefined function confirmation_path/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

In other places when i tried installing coherence: 0.3 
i got module Example.Coherence.PasswordController is not available
module Example.Coherence.RegistrationController is not available

But i got session controller working fine


Please help me here.

**Comment by smpallen99** [comment]
@Tenzil I'm unclear what you are trying to do. Are you trying to use coherence on your own project, or are you trying to get coherence_demo working? I'll clone a clean copy of coherence_demo and try it.

**Comment by smpallen99** [comment]
@Tenzil Try it now. I just updated to the coherence phx-1.3 branch. I ran `mix coherence.install --reinstall`.  There is one failing test case if you don't set the mailer env variables. The test runs fine when I set my own env variables for the mailer. This is more of an issue with coherence. I need to add a way to disable the mailer for testing. 

Let me know if it works for you please.
